[functions.export-cases-excel]
verify_jwt = true
entrypoint = "./functions/export-cases-excel/index.ts"

[functions.send-email]
verify_jwt = true
entrypoint = "./functions/send-email/index.ts"

[functions.admin-password]
verify_jwt = true
entrypoint = "./functions/admin-password/index.ts"

[functions.admin-client-management]
verify_jwt = true
entrypoint = "./functions/admin-client-management/index.ts"
